#ifndef _dev
#define _dev
# include <stdio.h>
# include <conio.h>
# include <bios.h>
# include <stdlib.h>
# include <process.h>
# include <time.h>
# include <c:\spe\Lib\cpu.h>
# include <c:\spe\Lib\vesa.h>
# include <c:\spe\Lib\xmouse.h>
//# include <c:\spe\Lib\disk.h>
# include <c:\spe\Lib\sound.h>



//char ERROR1	[50][50]=;
//processor management and other hardware devices

int CHECKHARDWARE()
{

return 0;
}
#endif